
const reviewArr = [
  {
    rating: 4.5,
    name: 'Mina Sorsok',
    age: 69,
    fitRating: 2.5,
    lengthRating: 3.0,
    qualityRating: 5.0,
    location: 'Melbourne, AU',
    size: 'M',
    reviewText: 'I\'m a 5\'1 female, but clothing geared towards women always seem to have tighter shoulder frames and cinched/inward waists. I\'m not a fan of that fit - I much prefer this loose, boxy fit. This parka is lightweight (and won\'t keep you warm), but it\'s a great layering outer piece.',
    reviewTitle: 'I LOVE IT',
  },
  {
    rating: 2.3,
    name: 'Caroline Cang',
    age: 24,
    fitRating: 3.4,
    lengthRating: 1.8,
    qualityRating: 4.5,
    location: 'Los Angeles, CA',
    size: 'S',
    reviewText: 'This item does a good job for a winter in LA. Anywhere else you would pretty much freeze.',
    reviewTitle: 'MEANT FOR LA WINTER',
  },
  {
    rating: 3.7,
    name: 'Alex Liu',
    age: 21,
    fitRating: 4.5,
    lengthRating: 2.7,
    qualityRating: 4.2,
    location: 'Beverly Hills, CA',
    size: 'XXL',
    reviewText: 'This parka looks great with both streetwear and more formal clothing. Love the generosity in sizing. I normally size up to XL for my jackets, coats, and sweaters, but L fit great and still had the oversized look I wanted.',
    reviewTitle: 'COMPLETES A LAYERED LOOK',
  },
  {
    rating: 1.5,
    name: 'Julie Im',
    age: 27,
    fitRating: 3.4,
    lengthRating: 4.0,
    qualityRating: 4.0,
    location: 'The Valley, CA',
    size: 'S',
    reviewText: 'beautiful PARKA. Read some reviews before order. I usually wear S, order XS instead. Still large. but good quality and it\'s so comfortable makes me keep it.',
    reviewTitle: 'LARGE',
  },
  {
    rating: 2.0,
    name: 'Gaby Pernama',
    age: 19,
    fitRating: 3.0,
    lengthRating: 2.5,
    qualityRating: 1.7,
    location: 'Chino Hills, CA',
    size: 'XS',
    reviewText: 'This is a cool oversized jacket--The style is meant to be big and boxy so I would suggest a much smaller size. I buy things in M usually but tried on an XS in store and it fit perfectly.',
    reviewTitle: 'GREAT OVERSIZED JACKET',
  },
  {
    rating: 4.0,
    name: 'Bryan Lee',
    age: 21,
    fitRating: 2.4,
    lengthRating: 4.2,
    qualityRating: 2.5,
    location: 'K-Town, CA',
    size: 'XXL',
    reviewText: 'versatile and awesome. Very happy with the purchase...',
    reviewTitle: 'MEANT FOR LA WINTER',
  },
  {
    rating: 2.7,
    name: 'Jennifer Haren',
    age: 29,
    fitRating: 2.7,
    lengthRating: 5.0,
    qualityRating: 5.0,
    location: 'Pallet Town, CA',
    size: 'S',
    reviewText: 'I\'ve been watching this jacket and got one for me and one for my husband....',
    reviewTitle: 'THE BEST ALL WEATHER JACKET',
  },
  {
    rating: 2.9,
    name: 'Andrew Ahn',
    age: 21,
    fitRating: 4.3,
    lengthRating: 2.7,
    qualityRating: 0.0,
    location: 'Hobak, Juk',
    size: 'XL',
    reviewText: 'My husband looks amazing and he can wear it in the fall winter layering and in the spring just as is. Thought it was going to be too oversized but it was just perfect.',
    reviewTitle: 'VERSATILE JACKET',
  },
];

module.exports = reviewArr;
